# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-robots

# Site settings
title: "Acorn Blog"
description: > # this means to ignore newlines until "email:"
   Must Read Book Summaries

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.svg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Acorn Editor'
author: 'Acorn Editor'
author_image: "/assets/images/author-avatar.jpg"

paginate:	5

url: "http://blog.acornx.ai" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#   - icon:	twitter
#     url:	https://twitter.com/dirkfabisch
#     desc: Follow me on twitter
#     share_url: http://twitter.com/share
#     share_title: ?text=
#     share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

  - icon:	tiktok
    url:	https://www.tiktok.com/@acornapp
    desc:	Follow me on TikTok
    share_url:
    share_title:
    share_link:

  - icon:	instagram
    url:	https://www.instagram.com/acorn.app/
    desc:	Follow me on instagram
    share_url:
    share_title:
    share_link:
